version: "3.8"
services:
  web:
    build: . 
    container_name: url_shortener_web
    ports:
      - "8000:8000"       
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shortener_db
      - JWT_SECRET=SUPERSECRETKEY
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MINUTES=30
      - CLEANUP_DAYS=30
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres:13
    container_name: url_shortener_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shortener_db
    volumes:
      - pgdata:/var/lib/postgresql/data  
  redis:
    image: redis:6-alpine
    container_name: url_shortener_redis
    ports:
      - "6379:6379"  
volumes:
  pgdata:
